const year2023 = [
  "Trump perp walk",
  "Twitter bankruptcy",
  "boat gets stuck",
  "Heat wave of 125°+",
  "51st state",
  "nukes used",
  "congressional brawl",
  "President Harris",
  "government shutdown",
  "major labor strike",
  "Elon runs for office",
  "New pandemic",
  "SCOTUS vacancy",
  "Aliens confirmed",
  "stock market crash",
  "Civil unrest",
  "Federal legalization of pot",
  "Gas under $3",
  "Congressperson removed from office",
  "National protests",
  "Putin dies",
  "Federal min wage increase",
  "Volcano erupts",
  "Biden impeached"
]