export const squaresData = {
  zoom: [
    "a/v trouble",
    "action item",
    "bandwidth",
    "bottom line",
    "breakout rooms",
    "can you see my screen?",
    "cat on camera",
    "circle back",
    "coffee shop noises",
    "deep dive",
    "dog on camera",
    "drill down",
    "ducks in a row",
    "follow up",
    "for the record",
    "game plan",
    "give it another minute",
    "happy ____day",
    "hard stop",
    "hit the ground running",
    "it is what it is",
    "kids on camera",
    "let me share my screen",
    "leverage",
    "low-hanging fruit",
    "mission critical",
    "moving parts",
    "next quarter",
    "next year",
    "no-brainer",
    "on my radar",
    "out-of-the-box",
    "pain points",
    "pivot",
    "put a pin in that",
    "reinvent the wheel",
    "scalable",
    "slide deck",
    "someone drinks coffee",
    "synergy",
    "take this offline",
    "tech debt",
    "this quarter",
    "unpack that",
    "value add",
    "win-win",
    "wrong window shared",
    "you're muted",
    "you're not muted"
  ],
}
